# Generated by Django 3.0.2 on 2022-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCacheStatus',
            fields=[
                ('cache_name', models.TextField(primary_key=True, serialize=False)),
                ('cache_type', models.TextField(choices=[('FILE', 'FILE'), ('MEMORY', 'MEMORY')])),
                ('status', models.TextField(choices=[('EMPTY', 'EMPTY'), ('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')])),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'unique_together': {('cache_name', 'cache_type')},
            },
        ),
    ]
