from msdat_python_api_settings.settings_common import *

#NOTE !!! values here will overwrite the values in settings_common
#FOR DEPLOYMENT TO PRODUCTION with database POSTGRESQL

"""
Django settings for msdat-python-api project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

###########################################################################################
##############################  ENV SPECIFIC SETTINGS #####################################
###########################################################################################

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0','*']

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "whomphd2",
        'USER': "dhisadmin",
        'PASSWORD':'9mQ50sTO38l8',
        'HOST':'localhost',
        'PORT':'5432'
    }
}