# Generated by Django 6.0.2 on 2026-02-18 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("profession", models.TextField(blank=True, null=True)),
                ("organization", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("newsletter", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("profession", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "managed": True,
            },
        ),
    ]
