# Generated by Django 3.0.2 on 2022-01-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datasource', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year_available', models.CharField(max_length=255)),
                ('period_available', models.CharField(max_length=255)),
                ('methodology', models.TextField()),
                ('subnational_data', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('multiplier_factor', models.IntegerField()),
                ('display_factor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('decription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('desirable_slope', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(max_length=255)),
                ('program_area', models.CharField(max_length=255)),
                ('national_target', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('national_source', models.CharField(blank=True, max_length=255, null=True)),
                ('national_information', models.CharField(blank=True, max_length=255, null=True)),
                ('sdg_target', models.CharField(blank=True, max_length=255, null=True)),
                ('sdg_information', models.CharField(blank=True, max_length=255, null=True)),
                ('first_related', models.IntegerField(blank=True, null=True)),
                ('second_related', models.IntegerField(blank=True, null=True)),
                ('third_related', models.IntegerField(blank=True, null=True)),
                ('fourth_related', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Factor')),
                ('group', models.ManyToManyField(blank=True, related_name='group_indicator', to='app_main.Group', verbose_name='the groups associated with this datasource')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocationHierarchyLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'managed': True,
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.LocationHierarchyLevel')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Indicator')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IndicatorValuetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Indicator')),
                ('valuetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.ValueType')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisaggregatedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[['MALE', 'MALE'], ['FEMALE', 'FEMALE']], max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Indicator')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Location')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.ValueType')),
            ],
        ),
        migrations.CreateModel(
            name='DatasourceValuetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('valuetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.ValueType')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatasourceSpecificIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datasource_indicator', models.CharField(max_length=255)),
                ('measurement_numerator', models.TextField()),
                ('measurement_denominator', models.TextField()),
                ('frequency', models.CharField(max_length=255)),
                ('methodology_estimation', models.TextField()),
                ('indicator_definition', models.TextField()),
                ('data_level', models.CharField(max_length=255)),
                ('national', models.BooleanField(blank=True, null=True)),
                ('zonal', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(blank=True, null=True)),
                ('senatorial', models.BooleanField(blank=True, null=True)),
                ('lga', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Indicator')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatasourceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Location')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_datasource', to='app_main.Group', verbose_name='the groups associated with this datasource'),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasources', models.ManyToManyField(related_name='dashboards', to='app_main.Datasource')),
                ('indicators', models.ManyToManyField(related_name='dashboards', to='app_main.Indicator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Datasource')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Indicator')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.Location')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.ValueType')),
            ],
            options={
                'managed': True,
                'unique_together': {('indicator', 'period', 'location', 'datasource', 'value_type')},
            },
        ),
    ]
