# Generated by Django 3.0.2 on 2022-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='datasources',
            field=models.ManyToManyField(related_name='indicators', to='app_main.Datasource'),
        ),
    ]
